import type { TdsCoverageProfile, TdsFile } from "./tds-types";

const legacyTdsFiles = [
  {
    id: "ptx-1200",
    fileName: "PTX-1200-Prof-Marroca-Coarse-Texture-TPX-Tint.pdf",
    fileUrl: null,
    manufacturer: "Plascon",
    productCode: "PTX 1200",
    productName: "Professional Marroca Coarse Texture",
    description: null,
    revision: null,
    revisionDate: null,
    packSizesLitres: [20],
    status: "needs-review",
    warnings: [],
    errorMessage: null,
    uploadedAt: new Date().toISOString(),
    profiles: [
      {
        id: "two-coat-stipple",
        name: "Two-coat stipple",
        applicationMethod: "Stipple",
        coverageM2PerLitre: 4,
        coverageBasis: "PER_COAT",
        coverageType: "PRACTICAL",
        recommendedCoats: 2,
        recommendedDftMicrons: null,
        recommendedWftMicrons: null,
        containerSizeLitres: 20,
        sourcePage: null,
        note: null,
        confidence: 0.96,
        isSelected: true,
      },
      {
        id: "one-coat-stipple",
        name: "One-coat stipple",
        applicationMethod: "Stipple",
        coverageM2PerLitre: 1.9,
        coverageBasis: "TOTAL_SYSTEM",
        coverageType: "PRACTICAL",
        recommendedCoats: 1,
        recommendedDftMicrons: null,
        recommendedWftMicrons: null,
        containerSizeLitres: 20,
        sourcePage: null,
        note: null,
        confidence: 0.98,
        isSelected: false,
      },
      {
        id: "even-spray",
        name: "Even spray",
        applicationMethod: "Spray",
        coverageM2PerLitre: 1,
        coverageBasis: "TOTAL_SYSTEM",
        coverageType: "PRACTICAL",
        recommendedCoats: 2,
        recommendedDftMicrons: null,
        recommendedWftMicrons: null,
        containerSizeLitres: 20,
        sourcePage: null,
        note: "Applied in two stages.",
        confidence: 0.98,
        isSelected: false,
      },
    ],
  },
  {
    id: "wall-and-all",
    fileName: "Wall-All.pdf",
    fileUrl: null,
    manufacturer: "Plascon",
    productCode: "PTX 4400",
    productName: "Wall & All",
    description: null,
    revision: null,
    revisionDate: null,
    packSizesLitres: [5],
    status: "imported",
    warnings: [],
    errorMessage: null,
    uploadedAt: new Date().toISOString(),
    profiles: [
      {
        id: "single-coat-roller",
        name: "Single-coat roller",
        applicationMethod: "Roller",
        coverageM2PerLitre: 8,
        coverageBasis: "TOTAL_SYSTEM",
        coverageType: "PRACTICAL",
        recommendedCoats: 1,
        recommendedDftMicrons: null,
        recommendedWftMicrons: null,
        containerSizeLitres: 5,
        sourcePage: null,
        note: null,
        confidence: 0.99,
        isSelected: true,
      },
      {
        id: "two-coat-brush",
        name: "Two-coat brush",
        applicationMethod: "Brush",
        coverageM2PerLitre: 6.5,
        coverageBasis: "PER_COAT",
        coverageType: "PRACTICAL",
        recommendedCoats: 2,
        recommendedDftMicrons: null,
        recommendedWftMicrons: null,
        containerSizeLitres: 5,
        sourcePage: null,
        note: null,
        confidence: 0.97,
        isSelected: false,
      },
    ],
  },
  {
    id: "cashmere",
    fileName: "Cashmere.pdf",
    fileUrl: null,
    manufacturer: "Plascon",
    productCode: "CSH 900",
    productName: "Cashmere Silk Sheen",
    description: null,
    revision: null,
    revisionDate: null,
    packSizesLitres: [5],
    status: "needs-review",
    warnings: ["Low-confidence coverage value requires review."],
    errorMessage: null,
    uploadedAt: new Date().toISOString(),
    profiles: [
      {
        id: "two-coat-roller",
        name: "Two-coat roller",
        applicationMethod: "Roller",
        coverageM2PerLitre: 9,
        coverageBasis: "PER_COAT",
        coverageType: "PRACTICAL",
        recommendedCoats: 2,
        recommendedDftMicrons: null,
        recommendedWftMicrons: null,
        containerSizeLitres: 5,
        sourcePage: null,
        note: null,
        confidence: 0.61,
        isSelected: true,
      },
    ],
  },
];

export const initialTdsFiles: TdsFile[] = legacyTdsFiles.map((file) => ({
  ...file,
  status: file.status as TdsFile["status"],
  packSizes: file.packSizesLitres.map((quantity) => ({
    quantity,
    uom: "L" as const,
    label: `${quantity} L`,
  })),
  profiles: file.profiles.map(
    (profile): TdsCoverageProfile => ({
      ...profile,
      applicationMethods: profile.applicationMethod
        ? [profile.applicationMethod]
        : [],
      rateMode: "COVERAGE",
      rateUnit: "M2_PER_L",
      rateMin: profile.coverageM2PerLitre,
      rateMax: profile.coverageM2PerLitre,
      coverageBasis:
        profile.coverageBasis as TdsCoverageProfile["coverageBasis"],
      coverageType: profile.coverageType as TdsCoverageProfile["coverageType"],
      recommendedCoatsMin: profile.recommendedCoats,
      recommendedCoatsMax: profile.recommendedCoats,
      thicknessMin:
        profile.recommendedDftMicrons ?? profile.recommendedWftMicrons,
      thicknessMax:
        profile.recommendedDftMicrons ?? profile.recommendedWftMicrons,
      thicknessUnit:
        profile.recommendedDftMicrons !== null ||
        profile.recommendedWftMicrons !== null
          ? "MICRON"
          : null,
      manufacturerRateLabel: null,
      sourceSnippet: null,
    }),
  ),
}));
