import type { PrismaClient } from "../generated/prisma/client";

export const materials = [
  {
    name: "Acrylic Glazecoat",
    sku: "CV82",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Acrylic Scumble Glaze",
    sku: "GSL2",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aerolak Fluorescent Spray Paint",
    sku: "91 20 01 - 04",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aerolak Metallic Spray Paint",
    sku: "91 10 13 - 20",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aerolak Regular Spray Paint",
    sku: "91 10 38 - 99, 99 01 04",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aerolak Special Finishes",
    sku: "91 10 54-56, 91 06 32",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "All Purpose Matt",
    sku: "PEM 800",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "All Purpose Matt Tint Base",
    sku: "TDA",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "All Purpose Undercoat",
    sku: "PU 800",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Ancillary Products",
    sku: "SS12",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aquarista White",
    sku: "PHB800",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aquarista Pastel Tint Base",
    sku: "THB1000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Aquasolv Degreaser",
    sku: "GR1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Arctic White",
    sku: "CAW1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Bakkie & Trailer Coating",
    sku: "BTC3",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Base Coat / Sealer",
    sku: "EZN",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Bituminous Aluminium Paint (One Pack)",
    sku: "RMB1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Bonding Liquid",
    sku: "CVI14",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Brick and Concrete Marking Paint",
    sku: "BTP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Brick and Slasto Dressing",
    sku: "TBD1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Brickseal",
    sku: "WBS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Brilliant White Gloss Enamel",
    sku: "PSB1000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Brush Cleaner",
    sku: "50 22 05",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Cashmere",
    sku: "CAS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Cashmere Tint Bases",
    sku: "TCA",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Cashmere Tester Pots",
    sku: "TCA",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Clear Lacquers",
    sku: "EZN",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Coastcote Etch Primer",
    sku: "SNK",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Colourants",
    sku: "PB-PV",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Concrete Floor Prep",
    sku: "FCS1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Contractors Matt",
    sku: "PEM600",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Contractors Matt Tint Base",
    sku: "TCP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Damp Plaster Paint",
    sku: "PSB600",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Dampseal",
    sku: "WDS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Double Velvet",
    sku: "VEL",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Double Velvet Tint Bases",
    sku: "TDV",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Double Velvet Tester Pots",
    sku: "TDV",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Easy Living Wall Master Matt",
    sku: "ELM",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Easy Living Multi Surface Sheen",
    sku: "ELS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Easy Living Gloss Enamel",
    sku: "ELE",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Easy Living Roof And Paving Paint",
    sku: "ELR",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "EPD Epoxy Floor Coating",
    sku: "EPD",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Economical Quick Drying Primer",
    sku: "QDP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Eggshell Enamel (Professional)",
    sku: "PSB700",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "RemovALL High Strength Cleaner & Degreaser",
    sku: "RCI",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "RemovALL High Performance Coatings Remover",
    sku: "RRH",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Ready Mixed Crack Filler",
    sku: "PRM1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Ripple Finish",
    sku: "99 01 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Road Line Paint Thinner",
    sku: "HVL1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Road Marking Paint (Non - SABS)",
    sku: "TP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Rockset",
    sku: "10 22 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Roof Paint (True Colour)",
    sku: "TCR (1 - 8)",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Sanding Sealer",
    sku: "SS15",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Schoolboard Paint",
    sku: "FOP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Silvershine Aluminium Paint (One Pack)",
    sku: "ASS1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Skim Coats - Exterior",
    sku: "PSE",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Skim Coats - Interior",
    sku: "PSI",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Stoep Enamel",
    sku: "SP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Suede",
    sku: "SDE",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Suede Tint Base",
    sku: "TSD1000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Sugar Soap Liquid",
    sku: "50 18 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Sugar Soap Powder",
    sku: "50 17 03",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Acrylic Polvin (Plascon)",
    sku: "EPL",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Acrylic Polvin Tint Bases (Plascon)",
    sku: "TAP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Universal Enamel (Plascon)",
    sku: "NY/G",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Universal Enamel Tint Bases (Plascon)",
    sku: "TSE",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Matt (Professional)",
    sku: "PEM900",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Matt Tint Bases (Professional)",
    sku: "TSA",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super Penetrating Stains",
    sku: "SPS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Super White Hycover",
    sku: "CNC1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Superior Low Sheen",
    sku: "PEM1000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Superior Low Sheen Tint Bases",
    sku: "TLS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Superior Matt",
    sku: "PEM950",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Superior Matt Tint Bases",
    sku: "TPM",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Superior Satin",
    sku: "PEM1100",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Superior Satin Tint Bases",
    sku: "THS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Synlac 2000",
    sku: "SL2000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Synlac 5000",
    sku: "SL5000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Synlac Industrial Enamels",
    sku: "SL",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tile & Melamine Primer",
    sku: "CTP1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Textured",
    sku: "UTX",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro High Hiding Matt",
    sku: "UHM",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Bright Matt",
    sku: "UBM",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Brilliant Sheen",
    sku: "ULS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Gloss Enamel",
    sku: "UWE",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Solvent-Based Primer",
    sku: "USP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Undercoat",
    sku: "UWU",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Tradepro Water-Based Primer",
    sku: "UWP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Bright Gloss",
    sku: "GTC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Bright Gloss Tint Bases",
    sku: "TGT2000",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Brilliant Sheen",
    sku: "STC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Brilliant Sheen Tint Bases",
    sku: "TTS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Fresh White",
    sku: "ATC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Primer, Sealer, Undercoat",
    sku: "PSU",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Textured",
    sku: "TTT",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Thick & Strong",
    sku: "MTC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "True Colour Thick & Strong Tint Bases",
    sku: "TTM",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Universal Shading Colours",
    sku: "PPC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Universal Undercoat",
    sku: "UC1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Velvaglo Satin",
    sku: "VLO",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Velvaglo Satin Tint Bases",
    sku: "TVG",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Velvaglo Non-Drip Water-based Enamel",
    sku: "VLW",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Velvaglo Non-Drip Water-based Enamel Tint Bases",
    sku: "TVW",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Wall & All",
    sku: "WAA",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Wall & All Tint Bases",
    sku: "TWA",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Wallseal",
    sku: "WAS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Wallseal Pastel Tint Base",
    sku: "TWS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Water-based Gypsum & Masonary Sealer",
    sku: "PGS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Water-based Penetrating Stains",
    sku: "WPS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Water-based Polyurethane (AquaNova)",
    sku: "WPU",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Water-based Sanding Sealer",
    sku: "SSW",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Waterproofing Compound",
    sku: "PWC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Wood Lacquers",
    sku: "WL",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Wood Primer",
    sku: "UC2",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "WoodCare Knot Seal",
    sku: "PK2",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "WoodCare Natural Deck Coating",
    sku: "WWV",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "WoodCare Sanding Sealer",
    sku: "SS16",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "WoodCare Sunproof",
    sku: "WSP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "WoodCare Ultra Varnish",
    sku: "X33 - 44",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "WoodCare Wood Preservative",
    sku: "FPR",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodfiller",
    sku: "90 25 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodcare Water-based Exterior Varnish",
    sku: "WSP 17 - 28",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodcare Water-based Exterior Varnish Tint bases Gloss",
    sku: "WST",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodcare Water-based Exterior Varnish Tint bases Suede",
    sku: "WSB",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodcare Water-based Interior Varnish",
    sku: "X45-51",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodcare Water-based Interior Varnish Tint bases Gloss",
    sku: "WUT",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Woodcare Water-based Interior Varnish Tint bases Suede",
    sku: "WUB",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Metal Water-based Primer",
    sku: "MWP1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Micatex",
    sku: "BBO",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Micatex Tint Bases",
    sku: "TMX",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Mild Steel Primer",
    sku: "UC501",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Mortalift",
    sku: "51 10 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Multiseal",
    sku: "VSS",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Multi-Surface Primer",
    sku: "WUP1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Nitrolac H/B Dual",
    sku: "ANL",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Nitrocellulose Lacquers",
    sku: "IL",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Nuroof Cool Acrylic Roof Paint",
    sku: "TRP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "One Coat Ceiling Paint",
    sku: "OCC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Paramount Gloss Enamel",
    sku: "PAR800",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Paramount Householders PVA",
    sku: "NLC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Paramount Plaster Primer: Water-based",
    sku: "PPW1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Paramount Universal Paint Stainers",
    sku: "33700-07",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Plascoguard 4000 HB",
    sku: "FHB",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plasclac Catalyst",
    sku: "KAT1104",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascoprime 207",
    sku: "UC207",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascoprime Self Etch Primer",
    sku: "SNS1",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascoguard 4000",
    sku: "FHB",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Plascosafe 500",
    sku: "PWI / TWI",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascosafe Water-based Floor Coating",
    sku: "WFC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascosafe Water-based Furniture Coatings",
    sku: "FFW",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascosafe Water-based Multicoat",
    sku: "FFW",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Plascothane 9000",
    sku: "PRT/PRH/PT",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascothane Catalyst",
    sku: "KAT518",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascothane Industrial Polyurethane Enamels",
    sku: "UP",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Plascosafe 18 Primer",
    sku: "EMS18",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascothane PureCoat",
    sku: "PUC",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Plascotuff 3000",
    sku: "PEX/PET/PEH",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascotuff Coal Tar Pitch Coating",
    sku: "EPD/EPT",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plascotuff Gehopon 3000 WB",
    sku: "GW",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Plaster Primer (Crown)",
    sku: "CPP2",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Plaster Primer (Plascon)",
    sku: "UC56",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Polyfilla Exterior",
    sku: "10 19 03",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Polyfilla Fine Crack Filler",
    sku: "10 18 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Polyfilla Interior",
    sku: "10 10 02",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Polyfilla Masonry Patching Plaster",
    sku: "10 20 03",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Polyfilla Mendall 90",
    sku: "80 16 01",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Polygalv Zinc Rich Primer",
    sku: "SN 176",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },

  {
    name: "Quick Drying Enamels",
    sku: "QDE",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
  {
    name: "Quicksand Primer Surfacer",
    sku: "PS202",
    supplierId: "cmmdxdol60009w8plpxqwnxct",
    categoryId: "cmmdxbuw40008w8plm4urs9ae",
  },
];

export async function seedMaterials(prisma: PrismaClient) {
  for (const material of materials) {
    await prisma.procurementProduct.upsert({
      where: { sku: material.sku },
      update: {
        name: material.name,
        supplierId: material.supplierId,
        categoryId: material.categoryId,
        isActive: true,
      },
      create: {
        name: material.name,
        sku: material.sku,
        supplierId: material.supplierId,
        categoryId: material.categoryId,
        isActive: true,
      },
    });
  }

  console.log(`Seeded ${materials.length} procurement materials`);
}
