import { prisma } from "@/lib/prisma";

const sites = [
  {
    code: "6770",
    name: "AFRIHOST 2026",
    client: "Mikebuyskes Construction",
    foreman: "Mawesi",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6771",
    name: "TSHAKUMA LATENT DEFECTS",
    client: "Mikebuyskes Construction",
    foreman: "Nic",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6772",
    name: "HOUGHTON UNIT 7410",
    client: "DIRECT",
    foreman: "Thousand",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6773",
    name: "39 COMMERCE SQUARE",
    client: "Direct",
    foreman: "OWEN",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6774",
    name: "CSI CPT",
    client: "Bantry",
    foreman: "Geofrey",
    specStatus: "REQUESTED",
  },
  {
    code: "6775",
    name: "10 POTGIETER ROAD EASTLEIGH EDENVALE",
    client: "Abbeydale",
    foreman: "Lucas",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6776",
    name: "41 CORAL HEIGHTS",
    client: "DIRET",
    foreman: "Geofrey",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6777",
    name: "THE INGRESS 2026",
    client: "ATTAQ",
    foreman: "Nic",
    specStatus: "RECEIVED",
  },
  {
    code: "6778",
    name: "ALBERTON MALL",
    client: "Mikebuyskes Construction",
    foreman: "Thousand",
    specStatus: "REQUESTED",
  },
  {
    code: "6779",
    name: "MOLETSI MALL",
    client: "Mikebuyskes Construction",
    foreman: "Mawesi",
    specStatus: "RECEIVED",
  },
  {
    code: "6780",
    name: "WW BOSKRUIN",
    client: "BANTRY",
    foreman: "Temba",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6781",
    name: "PAARDVLEI OFFICES",
    client: "Farquharson Construction",
    foreman: "Geofrey",
    specStatus: "REQUESTED",
  },
  {
    code: "6782",
    name: "BABCOCK BARTLETT",
    client: "EXCELSUS",
    foreman: "Lucas",
    specStatus: "REQUESTED",
  },
  {
    code: "6783",
    name: "MANSFIELD RES 2026",
    client: "DIRET",
    foreman: "Griffith",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6784",
    name: "CURRO KRUGERSDORP",
    client: "DIRET",
    foreman: "Temba",
    specStatus: "RECEIVED",
  },
  {
    code: "6785",
    name: "VIRGIN ACTIVE WEMBLEY",
    client: "W3O",
    foreman: "Geofrey",
    specStatus: "REQUESTED",
  },
  {
    code: "6786",
    name: "LDS SCHEERPOORT",
    client: "Millennium Construction (Pty) Ltd",
    foreman: "Temba",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6787",
    name: "PREMIER FOODS PH2",
    client: "Archstone Construction (PTY) LTD",
    foreman: "Lucas",
    specStatus: "REQUESTED",
  },
  {
    code: "6788",
    name: "MOA PHASE 2",
    client: "ATTAQ",
    foreman: "Sean",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6789",
    name: "OASIS 3055",
    client: "Abbeydale",
    foreman: "Geofrey",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6790",
    name: "INDLOVU 3058",
    client: "Abbeydale",
    foreman: "Geofrey",
    specStatus: "RECEIVED",
  },
  {
    code: "6791",
    name: "86 TWEEDALE",
    client: "DIRET",
    foreman: "Owen",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6792",
    name: "CCBSA MIDRAND",
    client: "DLR",
    foreman: "Nic",
    specStatus: "REQUESTED",
  },
  {
    code: "6793",
    name: "FOOD LOVERS BRACKENGATE",
    client: "Abbeydale",
    foreman: "Geofrey",
    specStatus: "REQUESTED",
  },
  {
    code: "6794",
    name: "UNIT 4 ROYAL PARK LANE",
    client: "Bartosch",
    foreman: "Owen",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6795",
    name: "OKAVANGO CROSSING",
    client: "DIRET",
    foreman: "Geofrey",
    specStatus: "RECEIVED",
  },
  {
    code: "6796",
    name: "WATERFALL ISLAMIC HOUSE 8",
    client: "SRP",
    foreman: "Nic",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6797",
    name: "WATERFALL ISLAMIC HOUSE 16A",
    client: "SRP",
    foreman: "Nic",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6798",
    name: "DICKINSON WAREHOUSE",
    client: "Abbeydale",
    foreman: "Geofrey",
    specStatus: "RECEIVED",
  },
  {
    code: "6799",
    name: "LXX SANDHURST REMEDIAL",
    client: "Tiber",
    foreman: "Lawrence",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6800",
    name: "CANTABELLA",
    client: "W3O",
    foreman: "Tshepo",
    specStatus: "RECEIVED",
  },
  {
    code: "6801",
    name: "ERF 1940,WITFONTEIN X102",
    client: "Ndwala",
    foreman: "Lucas",
    specStatus: "REQUESTED",
  },
  {
    code: "6802",
    name: "HAASENDAL GABLES ROAD MARKING",
    client: "DIRET",
    foreman: "Geofrey",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6803",
    name: "Upper East Side 2026",
    client: "UPPER EAST SIDE BODY CORPORATE",
    foreman: "Lucas",
    specStatus: "REQUESTED",
  },
  {
    code: "6804",
    name: "37 COMMERCE CRESCENT",
    client: "DIRET",
    foreman: "Owen",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6805",
    name: "25 SUNSET BLVD SERENGETI",
    client: "DIRET",
    foreman: "Lucas",
    specStatus: "REQUESTED",
  },
  {
    code: "6806",
    name: "1140 BUSHWILLOW PARK",
    client: "JTSON",
    foreman: "Lucas",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6807",
    name: "UNIT 2 19 HASWEL STREET OAKLANDS",
    client: "DIRET",
    foreman: "Thousand",
    specStatus: "REQUESTED",
  },
  {
    code: "6808",
    name: "43 ECCLESTON BOUNDARY WALL",
    client: "DIRET",
    foreman: "Lawrence",
    specStatus: "REQUESTED",
  },
  {
    code: "6809",
    name: "HOUSE TERRY",
    client: "SKYSTONE",
    foreman: "Griffith",
    specStatus: "REQUESTED",
  },
  {
    code: "6810",
    name: "61 SHEPHERD UNIT 8",
    client: "DIRET",
    foreman: "Owen",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6811",
    name: "ARROW PARK 2026",
    client: "Abbeydale",
    foreman: "Nic",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6812",
    name: "UNIT 4 43 CHESHAM ROAD",
    client: "Millennium",
    foreman: "Owen",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6813",
    name: "THE REEF SC",
    client: "STRIVE",
    foreman: "Thousand",
    specStatus: "RECEIVED",
  },
  {
    code: "6814",
    name: "PESTANA KRUGER LODGE",
    client: "MODUBUILD",
    foreman: "Thousand",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6815",
    name: "HS PO 07640&41",
    client: "RESPUBLICA",
    foreman: "Mawesi",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6816",
    name: "STOR-AGE BRAMLEY",
    client: "MADISON HOLDINGS",
    foreman: "Thousand",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6817",
    name: "GALAXIES INVESTMENT GROUP",
    client: "ALSIWORX",
    foreman: "Griffith",
    specStatus: "REQUESTED",
  },
  {
    code: "6818",
    name: "CHECKERS ROODEPOORT",
    client: "EXCELSUS",
    foreman: "Temba",
    specStatus: "REQUESTED",
  },
  {
    code: "6819",
    name: "CURRO CLAYVILLE",
    client: "DIRET",
    foreman: "Lucas",
    specStatus: "RECEIVED",
  },
  {
    code: "6820",
    name: "CHUMA MALL 2026",
    client: "DIRET",
    foreman: "Griffith",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6821",
    name: "LONGLAKES ERF 137",
    client: "Ndwala",
    foreman: "Lucas",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6822",
    name: "MILPARK DOCTORS ROOMS",
    client: "JCREFURB",
    foreman: "Lawrence",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6823",
    name: "2 TARENTAAL RD, SUNWARD",
    client: "DIRET",
    foreman: "Lucas",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6824",
    name: "EASTWOOD MID YEAR",
    client: "RESPUBLICA",
    foreman: "Mawesi",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6825",
    name: "4 MOLENAAR 2026",
    client: "Baucor",
    foreman: "Thousand",
    specStatus: "REQUESTED",
  },
  {
    code: "6826",
    name: "WEST CITY MIDYEAR 2026",
    client: "RESPUBLICA",
    foreman: "Mawesi",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6827",
    name: "CURRO HAZELDEAN PRE&PRIMARY SCHOOL",
    client: "DIRET",
    foreman: "Mawesi",
    specStatus: "RECEIVED",
  },
  {
    code: "6828",
    name: "CURRO HAZELDEAN HIGH SCHOOL",
    client: "DIRET",
    foreman: "Mawesi",
    specStatus: "RECEIVED",
  },
  {
    code: "6829",
    name: "STADIO WATERFALL",
    client: "DIRET",
    foreman: "Nic",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6830",
    name: "THE BLOCK MEAT COMPANY",
    client: "BARROW",
    foreman: "Lucas",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6831",
    name: "BOSCH PO1532",
    client: "DIRET",
    foreman: "Lucas",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6832",
    name: "THE FIELDS MIDYEAR 2026",
    client: "RESPUBLICA",
    foreman: "Lawrence",
    specStatus: "NOT_NEEDED",
  },
  {
    code: "6833",
    name: "MIA'S ANGLING WOODMEAD",
    client: "SRP",
    foreman: "Owen",
    specStatus: "REQUESTED",
  },
  {
    code: "6834",
    name: "21 SWANSEA",
    client: "DIRET",
    foreman: "Lawrence",
    specStatus: "NOT_REQUESTED",
  },
  {
    code: "6835",
    name: "GRIT OFFICE",
    client: "EXCELSUS",
    foreman: "Mawesi",
    specStatus: "NOT_REQUESTED",
  },
] as const;

async function main() {
  for (const site of sites) {
    await prisma.site.upsert({
      where: { code: site.code },
      update: {
        name: site.name,
        client: site.client,
        specStatus: site.specStatus as any,
        isActive: true,
      },
      create: {
        code: site.code,
        name: site.name,
        client: site.client,
        specStatus: site.specStatus as any,
        isActive: true,
      },
    });
  }

  console.log(`Seeded/updated ${sites.length} sites.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
