export const claimsData: Record<
  string,
  { siteNameKeyword: string; claimDay: number | "COC" }
> = {
  // GRIFFITH
  "5960": { siteNameKeyword: "City Centre Phase 7", claimDay: 18 },
  "6328": { siteNameKeyword: "CITY CENTRE PH8 PTN20", claimDay: 18 },
  "6461": { siteNameKeyword: "CITY CENTRE PH8 PTN22", claimDay: 18 },
  "6558": { siteNameKeyword: "AO EXPANSION", claimDay: 18 },
  "6691": {
    siteNameKeyword: "CITY CENTRE SHOP108, 109 -DR'S ROOMS",
    claimDay: 18,
  },
  "6748": { siteNameKeyword: "Lanseria business park", claimDay: "COC" },
  "6749": { siteNameKeyword: "10 ARABIAN 2026", claimDay: 15 },
  "6757": { siteNameKeyword: "517 BLAIR ATHOL", claimDay: "COC" },

  // THEMBA
  "5619": { siteNameKeyword: "RADISSON HOTEL", claimDay: 18 },
  "6435": { siteNameKeyword: "SEW EURODRIVE AEROTON", claimDay: 18 },
  "6497": { siteNameKeyword: "HOUSE HARILAL", claimDay: 18 },
  "6573": { siteNameKeyword: "FLEURHOF MALL", claimDay: 20 },
  "6584": { siteNameKeyword: "LERATONG CITY MALL", claimDay: 5 },
  "6586": { siteNameKeyword: "DIMAKO TRANDFORMERS", claimDay: 10 },
  "6729": { siteNameKeyword: "IPROP WAREHOUSE", claimDay: "COC" },
  "6746": { siteNameKeyword: "THE FALLS SC", claimDay: 15 },

  // LAWRENCE
  "6316": { siteNameKeyword: "SANDTON GATE PH2", claimDay: 15 },
  "6381": { siteNameKeyword: "ST JOHNS PREP SCHOOL", claimDay: "COC" },
  "6450": { siteNameKeyword: "One Rosbank Phase 2", claimDay: 18 },
  "6595": { siteNameKeyword: "RACE SANDTON", claimDay: 18 },
  "6616": {
    siteNameKeyword: "OXGLEN BUILDING 2 PARAPET WATERPROOFING",
    claimDay: "COC",
  },
  "6632": { siteNameKeyword: "ONE ROSEBANK MAINTENANCE", claimDay: "COC" },
  "6659": { siteNameKeyword: "ST JOHNS DRAMA ROOM", claimDay: 18 },
  "6660": { siteNameKeyword: "5 ST MARKS 2026", claimDay: 18 },
  "6694": { siteNameKeyword: "SANDTON GATE PH1", claimDay: "COC" },
  "6709": { siteNameKeyword: "CAR TRACK TOUCH UPS", claimDay: "COC" },
  "6712": { siteNameKeyword: "BARROW YARD", claimDay: "COC" },
  "6727": { siteNameKeyword: "OLYMPUS", claimDay: "COC" },
  "6750": { siteNameKeyword: "COCA COLA WATER DAMAGE", claimDay: "COC" },

  // THOUSAND
  "5083": { siteNameKeyword: "19 Ridge Road", claimDay: 15 },
  "6358": { siteNameKeyword: "THE HOUGHTON HOTEL", claimDay: 22 },
  "6388": { siteNameKeyword: "ST LUKES SCHOOL", claimDay: 18 },
  "6407": { siteNameKeyword: "KSB", claimDay: 15 },
  "6426": { siteNameKeyword: "Brookfields", claimDay: 15 },
  "6475": { siteNameKeyword: "GPM Krishna", claimDay: 15 },
  "6543": { siteNameKeyword: "LIBERTY CANTEEN", claimDay: 15 },
  "6617": { siteNameKeyword: "MOTUS HO PH2", claimDay: 15 },
  "6634": {
    siteNameKeyword: "THUTHUKA PACKING DIE CUTTER",
    claimDay: 18,
  },
  "6690": { siteNameKeyword: "HILL ON EMPIRE", claimDay: "COC" },
  "6715": { siteNameKeyword: "35 LINDEN ROAD BRAMLEY", claimDay: "COC" },
  "6726": { siteNameKeyword: "RACEWAY 2026", claimDay: "COC" },
  "6731": { siteNameKeyword: "THE NEIGHBOURHOOD GATE HOUSE", claimDay: 20 },

  // LUCAS
  "6102": { siteNameKeyword: "26 POMONA", claimDay: 18 },
  "6248": { siteNameKeyword: "Crusaders Ph2", claimDay: 18 },
  "6312": { siteNameKeyword: "RIVERFIELDS X97", claimDay: 18 },
  "6356": { siteNameKeyword: "EASTPORT SPEC 5", claimDay: 18 },
  "6357": { siteNameKeyword: "THE SIGNATURE TYPE H", claimDay: 18 },
  "6525": { siteNameKeyword: "RIVERFIELDS X57", claimDay: 18 },
  "6541": { siteNameKeyword: "CURRUSEAL BOKSBURG", claimDay: 18 },
  "6605": { siteNameKeyword: "BREDELL SPEC WAREHOUSE", claimDay: 18 },
  "6620": { siteNameKeyword: "ENSTRA 2025", claimDay: 18 },
  "6627": { siteNameKeyword: "CATERPILLAR", claimDay: 18 },
  "6643": { siteNameKeyword: "iTONKA SQUARE PH3", claimDay: 29 },
  "6647": { siteNameKeyword: "HEINEKEN SPRINGS", claimDay: 15 },
  "6658": { siteNameKeyword: "CHAMBERLAIN EASTRAND", claimDay: 15 },
  "6688": { siteNameKeyword: "AIRPORT STRATEGIC PARK", claimDay: 18 },
  "6698": { siteNameKeyword: "THE SIGNATURE UNIT 192", claimDay: "COC" },
  "6711": { siteNameKeyword: "THE SIGNATURE UNIT 11", claimDay: "COC" },
  "6723": { siteNameKeyword: "MANITOU EXTERIOR", claimDay: "COC" },
  "6740": { siteNameKeyword: "ISANDO ENTYCE", claimDay: 15 },
  "6743": { siteNameKeyword: "ISANDO SNACKWORK", claimDay: 15 },
  "6752": { siteNameKeyword: "Signature latent defects", claimDay: 18 },
  "6753": { siteNameKeyword: "CT Hydraulics", claimDay: 18 },

  // OWEN
  "5535": { siteNameKeyword: "REED RESIDENCE", claimDay: "COC" },
  "6517": { siteNameKeyword: "POSTHOUSE LINK", claimDay: 20 },
  "6520": { siteNameKeyword: "COMMERCE SQUARE", claimDay: 20 },
  "6589": { siteNameKeyword: "MONTE CIRCLE BUILDING A", claimDay: "COC" },
  "6596": { siteNameKeyword: "ITALTILE BRYANSTON", claimDay: "COC" },
  "6602": { siteNameKeyword: "M&D HO", claimDay: 18 },
  "6618": { siteNameKeyword: "KATHERINE TOWERS", claimDay: "COC" },
  "6637": { siteNameKeyword: "AIE GREENSIDE TOP FLOOR", claimDay: 15 },
  "6645": { siteNameKeyword: "CHAMBERLAIN RANDBURG 2025", claimDay: "COC" },
  "6667": { siteNameKeyword: "SASANI AFRICA", claimDay: 15 },
  "6669": { siteNameKeyword: "HURLINGHAM GATE", claimDay: "COC" },
  "6677": { siteNameKeyword: "83 Protea", claimDay: 10 },
  "6679": { siteNameKeyword: "CULROSS BUILDING 7", claimDay: 18 },
  "6717": { siteNameKeyword: "JTDOOLEY OFFICES", claimDay: "COC" },
  "6730": { siteNameKeyword: "AKARU UNIT 07", claimDay: "COC" },
  "6735": { siteNameKeyword: "BARROW OFFICES", claimDay: 18 },
  "6744": { siteNameKeyword: "THE GRANDE UNIT 12", claimDay: "COC" },
  "6755": { siteNameKeyword: "HAMPTON OFFICE PARK", claimDay: 18 },
  "6763": { siteNameKeyword: "CULROSS BUILDING 6", claimDay: 18 },
  "6766": { siteNameKeyword: "SANDTON CITY E-HAILING", claimDay: 15 },

  // NICOLAS
  "6156": { siteNameKeyword: "The precinct", claimDay: 10 },
  "6451": { siteNameKeyword: "WOOLWORTHS DC PHASE2", claimDay: 18 },
  "6471": {
    siteNameKeyword: "GATEWAY EAST WATERFFALL CITY",
    claimDay: 18,
  },
  "6511": { siteNameKeyword: "ETWATWA CROSSING", claimDay: 20 },
  "6551": {
    siteNameKeyword: "ISLAMIC INSTITUTE MOSQUE",
    claimDay: 22,
  },
  "6590": {
    siteNameKeyword: "MIDRAND WAREHOUSE 5 OFFICES",
    claimDay: 8,
  },
  "6599": { siteNameKeyword: "CHARLESTON LODGE", claimDay: 18 },
  "6662": {
    siteNameKeyword: "MIDRAND HQ SERVICES HQ",
    claimDay: 18,
  },
  "6663": { siteNameKeyword: "RIETVLEI BP -RUGGED SA", claimDay: 14 },
  "6664": { siteNameKeyword: "RIETVLEI BP -PACKAGE IT", claimDay: 14 },
  "6680": { siteNameKeyword: "VLEI LODGE PHINDA", claimDay: 11 },
  "6682": { siteNameKeyword: "MIDRAND WAREHOUSE 7", claimDay: 8 },
  "6706": { siteNameKeyword: "IBP CONSTRUCTION", claimDay: "COC" },
  "6710": { siteNameKeyword: "HEREFORD COMPLEX", claimDay: "COC" },
  "6714": { siteNameKeyword: "MANN ROAD WAREHOUSE", claimDay: 18 },
  "6716": { siteNameKeyword: "KINGS WALK MALL", claimDay: 18 },
  "6720": { siteNameKeyword: "DHL WATERFALL SCAFFOLDING", claimDay: "COC" },
  "6722": {
    siteNameKeyword: "MIDSTREM MEDICLINIC DR'S ROOMS",
    claimDay: "COC",
  },
  "6732": {
    siteNameKeyword: "IRENE LINK BUILDING B",
    claimDay: "COC",
  },
  "6741": {
    siteNameKeyword: "ELLIPSE UNIT 2015&4909",
    claimDay: "COC",
  },
  "6751": { siteNameKeyword: "AMATOLA DEVELOPMENT", claimDay: 20 },
  "6762": { siteNameKeyword: "IRENE LINK D REMEDIAL", claimDay: "COC" },
};
