import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client.js";

const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

type SiteClientSeed = {
  code: string;
  client: string;
};

function normalizeClientName(value: string) {
  return value.trim().replace(/\s+/g, " ");
}

const siteClientSeeds: SiteClientSeed[] = [
  { code: "6000", client: "JCRefurb" },
  { code: "6001", client: "Libera" },
  { code: "6002", client: "REDEFINE" },
  { code: "6003", client: "JTSON" },
  { code: "6004", client: "Mikebuyskes" },
  { code: "6005", client: "Barrow" },
  { code: "6006", client: "Hkampman" },
  { code: "6007", client: "Mikebuyskes" },
  { code: "6008", client: "SRP Development" },
  { code: "6009", client: "Bantry" },
  { code: "6010", client: "Direct" },
  { code: "6011", client: "Direct" },
  { code: "6012", client: "Isipani" },
  { code: "6013", client: "FCP" },
  { code: "6014", client: "Valobex" },
  { code: "6015", client: "Probest Projects (PTY) LTD" },
  { code: "6016", client: "Bantry" },
  { code: "6017", client: "Bondev" },
  { code: "6018", client: "Abbeycape" },
  { code: "6019", client: "Baucor" },
  { code: "6020", client: "LVProjects" },
  { code: "6021", client: "Isipani" },
  { code: "6022", client: "RICP" },
  { code: "6023", client: "RESPUBLICA" },
  { code: "6024", client: "Direct" },
  { code: "6025", client: "Direct" },
  { code: "6026", client: "Rocon" },
  { code: "6027", client: "RESPUBLICA" },
  { code: "6028", client: "JTSon" },
  { code: "6029", client: "Abbeydale" },
  { code: "6030", client: "Direct" },
  { code: "6031", client: "Direct" },
  { code: "6032", client: "Abbeydale" },
  { code: "6033", client: "Direct" },
  { code: "6034", client: "Caveleros" },
  { code: "6035", client: "FirstClass Projects" },
  { code: "6036", client: "Abbeydale" },
  { code: "6037", client: "DLR" },
  { code: "6038", client: "WBHO" },
  { code: "6039", client: "Direct" },
  { code: "6040", client: "Direct" },
  { code: "6041", client: "Direct" },
  { code: "6042", client: "FRAMECORE CONSTRUCTION" },
  { code: "6043", client: "JTDooley" },
  { code: "6044", client: "Farquharson Construction" },
  { code: "6045", client: "Millcon" },
  { code: "6046", client: "Direct" },
  { code: "6047", client: "African Kingdom Holdings" },
  { code: "6048", client: "JTDooley" },
  { code: "6049", client: "Baucor" },
  { code: "6050", client: "Bantry" },
  { code: "6051", client: "Baucor" },
  { code: "6052", client: "RESPUBLICA" },
  { code: "6053", client: "Broll" },
  { code: "6054", client: "JCRefurb" },
  { code: "6055", client: "Direct" },
  { code: "6056", client: "Skystone" },
  { code: "6057", client: "Direct" },
  { code: "6058", client: "M&D Construction" },
  { code: "6059", client: "Alchemy Props" },
  { code: "6060", client: "Direct" },
  { code: "6061", client: "BJV" },
  { code: "6062", client: "Direct" },
  { code: "6063", client: "Millcon" },
  { code: "6064", client: "Millcon" },
  { code: "6065", client: "M&D Construction" },
  { code: "6066", client: "Alchemy Props" },
  { code: "6067", client: "Trencon Construction" },
  { code: "6068", client: "Abbeydale" },
  { code: "6069", client: "Farquharson Construction" },
  { code: "6070", client: "Curasure" },
  { code: "6071", client: "Direct" },
  { code: "6072", client: "Direct" },
  { code: "6073", client: "Abbeydale" },
  { code: "6074", client: "Redefine" },
  { code: "6075", client: "WBHO" },
  { code: "6076", client: "FirstClass Projects" },
  { code: "6077", client: "WBHO" },
  { code: "6078", client: "MBC" },
  { code: "6079", client: "Alchemy Props" },
  { code: "6080", client: "Direct" },
  { code: "6081", client: "Probest Projects (PTY) LTD" },
  { code: "6082", client: "Direct" },
  { code: "6083", client: "DLR" },
  { code: "6084", client: "GDM Group" },
  { code: "6085", client: "Tricolt" },
  { code: "6086", client: "Bondev" },
  { code: "6087", client: "Bondev" },
  { code: "6088", client: "Bartosch Construction" },
  { code: "6089", client: "Direct" },
  { code: "6090", client: "Barrow" },
  { code: "6091", client: "GDM Group" },
  { code: "6092", client: "JTDooley" },
  { code: "6093", client: "Direct" },
  { code: "6094", client: "Direct" },
  { code: "6095", client: "Direct" },
  { code: "6096", client: "Abbeycape" },
  { code: "6097", client: "Hkampman" },
  { code: "6098", client: "Barrow" },
  { code: "6099", client: "LVProjects" },
  { code: "6100", client: "LVProjects" },
  { code: "6101", client: "JCRefurb" },
  { code: "6102", client: "Bantry" },
  { code: "6103", client: "Mikebuyskes" },
  { code: "6104", client: "Central Developments" },
  { code: "6105", client: "Menlyn Maine" },
  { code: "6106", client: "MBC" },
  { code: "6107", client: "Direct" },
  { code: "6108", client: "Archstone Construction (PTY) LTD" },
  { code: "6109", client: "MBC" },
  { code: "6110", client: "Skystone" },
  { code: "6111", client: "Edilcon Construction (Pty) Ltd" },
  { code: "6112", client: "JCRefurb" },
  { code: "6113", client: "Edilcon Construction (Pty) Ltd" },
  { code: "6114", client: "Direct" },
  { code: "6115", client: "Direct" },
  { code: "6116", client: "FRAMECORE CONSTRUCTION" },
  { code: "6117", client: "DLR" },
  { code: "6118", client: "SRP Development" },
  { code: "6119", client: "Direct" },
  { code: "6120", client: "JTDooley" },
  { code: "6121", client: "Direct" },
  { code: "6122", client: "JTDooley" },
  { code: "6123", client: "Bondev" },
  { code: "6124", client: "M&M CONSTRUCTION" },
  { code: "6125", client: "Probest Projects (PTY) LTD" },
  { code: "6126", client: "Jovan" },
  { code: "6127", client: "Barrow" },
  { code: "6128", client: "Abbeycape" },
  { code: "6129", client: "Barrow" },
  { code: "6130", client: "Redefine" },
  { code: "6131", client: "GDM Group" },
  { code: "6132", client: "FRAMECORE CONSTRUCTION" },
  { code: "6133", client: "Barrow" },
  { code: "6134", client: "Direct" },
  { code: "6135", client: "RESPUBLICA" },
  { code: "6136", client: "SRP Development" },
  { code: "6137", client: "Baucor" },
  { code: "6138", client: "Versus" },
  { code: "6139", client: "Direct" },
  { code: "6140", client: "Direct" },
  { code: "6141", client: "Redefine" },
  { code: "6142", client: "Redefine" },
  { code: "6143", client: "Barrow" },
  { code: "6144", client: "Direct" },
  { code: "6145", client: "JCRefurb" },
  { code: "6146", client: "Libera" },
  { code: "6147", client: "Isipani" },
  { code: "6148", client: "Versus" },
  { code: "6149", client: "Versus" },
  { code: "6150", client: "JTDooley" },
  { code: "6151", client: "Direct" },
  { code: "6152", client: "Baucor" },
  { code: "6153", client: "JTDooley" },
  { code: "6154", client: "JTSon" },
  { code: "6155", client: "Airclima" },
  { code: "6156", client: "Archstone Construction (PTY) LTD" },
  { code: "6157", client: "Jovan" },
  { code: "6158", client: "Tri-Star" },
  { code: "6159", client: "Archstone Construction (PTY) LTD" },
  { code: "6160", client: "Jovan" },
  { code: "6161", client: "Bantry" },
  { code: "6162", client: "Excelsus" },
  { code: "6163", client: "Baucor" },
  { code: "6164", client: "Barrow" },
  { code: "6165", client: "Baucor" },
  { code: "6166", client: "Barrow" },
  { code: "6167", client: "JTSon" },
  { code: "6168", client: "Direct" },
  { code: "6169", client: "Bantry" },
  { code: "6170", client: "NDWALA(FARQUHARSON BEE)" },
  { code: "6171", client: "Abbeydale" },
  { code: "6172", client: "Baucor" },
  { code: "6173", client: "African Kingdom Holdings" },
  { code: "6174", client: "Archstone Construction (PTY) LTD" },
  { code: "6175", client: "Redefine" },
  { code: "6176", client: "RESPUBLICA" },
  { code: "6177", client: "Abbeycape" },
  { code: "6178", client: "FRAMECORE CONSTRUCTION" },
  { code: "6179", client: "Direct" },
  { code: "6180", client: "Direct" },
  { code: "6181", client: "MLC" },
  { code: "6182", client: "Millcon" },
  { code: "6183", client: "Baucor" },
  { code: "6184", client: "Redefine" },
  { code: "6185", client: "Redefine" },
  { code: "6186", client: "Direct" },
  { code: "6187", client: "Archstone Construction (PTY) LTD" },
  { code: "6188", client: "Broll" },
  { code: "6189", client: "MBC" },
  { code: "6190", client: "JTDooley" },
  { code: "6191", client: "Redefine" },
  { code: "6192", client: "Millcon" },
  { code: "6193", client: "Tiber" },
  { code: "6194", client: "Redefine" },
  { code: "6195", client: "W3O" },
  { code: "6196", client: "Barrow" },
  { code: "6197", client: "Jovan" },
  { code: "6198", client: "Metrum" },
  { code: "6199", client: "RESPUBLICA" },
  { code: "6200", client: "Direct" },
  { code: "6201", client: "RICP" },
  { code: "6202", client: "Barrow" },
  { code: "6203", client: "JTSon" },
  { code: "6204", client: "African Kingdom Holdings" },
  { code: "6205", client: "Airwaves" },
  { code: "6206", client: "Direct" },
  { code: "6207", client: "Skystone" },
  { code: "6208", client: "NDWALA(FARQUHARSON BEE)" },
  { code: "6209", client: "Direct" },
  { code: "6210", client: "Baucor" },
  { code: "6211", client: "RESPUBLICA" },
  { code: "6212", client: "RESPUBLICA" },
  { code: "6213", client: "Mikebuyskes" },
  { code: "6214", client: "Metrum" },
  { code: "6215", client: "Direct" },
  { code: "6216", client: "MBC" },
  { code: "6217", client: "Excelsus" },
  { code: "6218", client: "MADISON HOLDING" },
  { code: "6219", client: "True Prop" },
  { code: "6220", client: "RESPUBLICA" },
  { code: "6221", client: "Abbeydale" },
  { code: "6222", client: "Farquharson Construction" },
  { code: "6223", client: "Barrow" },
  { code: "6224", client: "Direct" },
  { code: "6225", client: "GDM Group" },
  { code: "6226", client: "Farquharson Construction" },
  { code: "6227", client: "African Kingdom Holdings" },
  { code: "6228", client: "Jovan" },
  { code: "6229", client: "Jovan" },
  { code: "6230", client: "Abbeycape" },
  { code: "6231", client: "Direct" },
  { code: "6232", client: "Baucor" },
  { code: "6233", client: "Direct" },
  { code: "6234", client: "Bantry" },
  { code: "6235", client: "Respublica" },
  { code: "6236", client: "Tricolt" },
  { code: "6237", client: "Cavaleros" },
  { code: "6238", client: "Tiber" },
  { code: "6239", client: "JTDooley" },
  { code: "6240", client: "Hexad" },
  { code: "6241", client: "Abbeycape" },
  { code: "6242", client: "GDM Group" },
  { code: "6243", client: "Excelsus" },
  { code: "6244", client: "DLR" },
  { code: "6245", client: "JTDooley" },
  { code: "6246", client: "Bantry" },
  { code: "6247", client: "Cavaleros" },
  { code: "6248", client: "Archstone Construction (PTY) LTD" },
  { code: "6249", client: "JTDooley" },
  { code: "6250", client: "JTSon" },
  { code: "6251", client: "Direct" },
  { code: "6252", client: "Bantry" },
  { code: "6253", client: "Bantry" },
  { code: "6254", client: "Barrow" },
  { code: "6255", client: "JTDooley" },
  { code: "6256", client: "Mikebuyskes Construction" },
  { code: "6257", client: "Direct" },
  { code: "6258", client: "Direct" },
  { code: "6259", client: "MBC" },
  { code: "6260", client: "JTDooley" },
  { code: "6261", client: "SRP Development" },
  { code: "6262", client: "Excelsus" },
  { code: "6263", client: "Respublica" },
  { code: "6264", client: "Respublica" },
  { code: "6265", client: "Respublica" },
  { code: "6266", client: "Respublica" },
  { code: "6267", client: "Respublica" },
  { code: "6268", client: "Respublica" },
  { code: "6269", client: "GDM Group" },
  { code: "6270", client: "Direct" },
  { code: "6271", client: "Capex" },
  { code: "6272", client: "JTSon" },
  { code: "6273", client: "Direct" },
  { code: "6274", client: "Project Lab" },
  { code: "6275", client: "LV Projects" },
  { code: "6276", client: "Direct" },
  { code: "6277", client: "JCRefurb" },
  { code: "6278", client: "Respublica" },
  { code: "6279", client: "Respublica" },
  { code: "6280", client: "PROBEST Projects (PTY) LTD" },
  { code: "6281", client: "Direct" },
  { code: "6282", client: "Direct" },
  { code: "6283", client: "Direct" },
  { code: "6284", client: "FirstClass Projects" },
  { code: "6285", client: "GDM Group" },
  { code: "6286", client: "Direct" },
  { code: "6287", client: "FRAMECORE CONSTRUCTION" },
  { code: "6288", client: "FirstClass Projects" },
  { code: "6289", client: "Mikebuyskes Construction" },
  { code: "6290", client: "Direct" },
  { code: "6291", client: "Baucor" },
  { code: "6292", client: "Millennium Construction (Pty) Ltd" },
  { code: "6293", client: "BANTRY" },
  { code: "6294", client: "Mikebuyskes Construction" },
  { code: "6295", client: "SRP DEVELOPMENT" },
  { code: "6296", client: "RDF" },
  { code: "6297", client: "DIRECT" },
  { code: "6298", client: "Abbeycape" },
  { code: "6299", client: "GDM Group" },
  { code: "6300", client: "JTDOOLEY" },
  { code: "6301", client: "LV Projects" },
  { code: "6302", client: "W30" },
  { code: "6303", client: "DIRECT" },
  { code: "6304", client: "Mikebuyskes Construction" },
  { code: "6305", client: "RICP" },
  { code: "6306", client: "GDM" },
  { code: "6307", client: "BARROW" },
  { code: "6308", client: "WBHO" },
  { code: "6309", client: "DIRECT" },
  { code: "6310", client: "Abbeycape" },
  { code: "6311", client: "Mikebuyskes Construction" },
  { code: "6312", client: "JTSON" },
  { code: "6313", client: "JTSON" },
  { code: "6314", client: "JTDOOLEY" },
  { code: "6315", client: "Direct" },
  { code: "6316", client: "Tiber" },
  { code: "6317", client: "Abbeydale" },
  { code: "6318", client: "Direct" },
  { code: "6319", client: "WBHO" },
  { code: "6320", client: "Origin" },
  { code: "6321", client: "Bantry" },
  { code: "6322", client: "DLR" },
  { code: "6323", client: "Direct" },
  { code: "6324", client: "Direct" },
  { code: "6325", client: "TEKCENT" },
  { code: "6326", client: "DIRECT" },
  { code: "6327", client: "AFRICAN KINGDOM HOLDING" },
  { code: "6328", client: "WBHO" },
  { code: "6329", client: "LV Projects" },
  { code: "6330", client: "Direct" },
  { code: "6331", client: "Baucor" },
  { code: "6332", client: "Mikebuyskes Construction" },
  { code: "6333", client: "Mikebuyskes Construction" },
  { code: "6334", client: "DIRECT" },
  { code: "6335", client: "Curasure" },
  { code: "6336", client: "JTDOOLEY" },
  { code: "6337", client: "BANTRY" },
  { code: "6338", client: "Farquharson Construction" },
  { code: "6339", client: "BANTRY" },
  { code: "6340", client: "Millennium Construction (Pty) Ltd" },
  { code: "6341", client: "DIRECT" },
  { code: "6342", client: "ATTACQ" },
  { code: "6343", client: "Abbeydale" },
  { code: "6344", client: "REDEFINE" },
  { code: "6345", client: "Mikebuyskes Construction" },
  { code: "6346", client: "FRAMECORE CONSTRUCTION" },
  { code: "6347", client: "Bantry" },
  { code: "6348", client: "CITY PROPERTY" },
  { code: "6349", client: "ABBEYDALE" },
  { code: "6350", client: "DIRECT" },
  { code: "6351", client: "Broll" },
  { code: "6352", client: "WBHO" },
  { code: "6353", client: "BANTRY" },
  { code: "6354", client: "ABBEYDALE" },
  { code: "6355", client: "Mikebuyskes Construction" },
  { code: "6356", client: "BANTRY" },
  { code: "6357", client: "AFRICAN KINGDOM HOLDING" },
  { code: "6358", client: "DIRECT" },
  { code: "6359", client: "Archstone Construction" },
  { code: "6360", client: "GDM" },
  { code: "6361", client: "JTDOOLEY" },
  { code: "6362", client: "Direct" },
  { code: "6363", client: "Direct" },
  { code: "6364", client: "Tricolt" },
  { code: "6365", client: "Direct" },
  { code: "6366", client: "Abbeycape" },
  { code: "6367", client: "Abbeycape" },
  { code: "6368", client: "Abbeydale" },
  { code: "6369", client: "BANTRY" },
  { code: "6370", client: "DIRECT" },
  { code: "6371", client: "W30" },
  { code: "6372", client: "M&M CONSTRUCTION" },
  { code: "6373", client: "DIRECT" },
  { code: "6374", client: "HKAMPMAN" },
  { code: "6375", client: "BANTRY" },
  { code: "6376", client: "SKYSTONE" },
  { code: "6377", client: "Archstone Construction (PTY) LTD" },
  { code: "6378", client: "DIRECT" },
  { code: "6379", client: "ISIPANI" },
  { code: "6380", client: "DIRECT" },
  { code: "6381", client: "JT DOOLEY" },
  { code: "6382", client: "Baucor" },
  { code: "6383", client: "DIRECT" },
  { code: "6384", client: "EXCELSUS" },
  { code: "6385", client: "DIRECT" },
  { code: "6386", client: "DIRECT" },
  { code: "6387", client: "Metrum" },
  { code: "6388", client: "NDWALA(FARQUHARSON BEE)" },
  { code: "6389", client: "Millennium Construction (Pty) Ltd" },
  { code: "6390", client: "Murray and Dickson" },
  { code: "6391", client: "DIRECT" },
  { code: "6392", client: "RESPUBLICA" },
  { code: "6393", client: "DIRECT" },
  { code: "6394", client: "JTDOOLEY" },
  { code: "6395", client: "DIRECT" },
  { code: "6396", client: "GDM" },
  { code: "6397", client: "AFRICAN KINGDOM HOLDING" },
  { code: "6398", client: "BARROW" },
  { code: "6399", client: "Direct" },
  { code: "6400", client: "Direct" },
  { code: "6401", client: "DIRECT" },
  { code: "6402", client: "GROWTHPOINT" },
  { code: "6403", client: "ABBEYDALE" },
  { code: "6404", client: "DIRECT" },
  { code: "6405", client: "GDM" },
  { code: "6406", client: "NDWALA(FARQUHARSON BEE)" },
  { code: "6407", client: "HEXAD" },
  { code: "6408", client: "Mikebuyskes Construction" },
  { code: "6409", client: "Archstone Construction (PTY) LTD" },
  { code: "6410", client: "FRAMECORE CONSTRUCTION" },
  { code: "6411", client: "DLR" },
  { code: "6412", client: "DIRECT" },
  { code: "6413", client: "Mikebuyskes Construction" },
  { code: "6414", client: "DIRECT" },
  { code: "6415", client: "Bartosch Construction" },
  { code: "6416", client: "Bantry" },
  { code: "6417", client: "DIRECT" },
  { code: "6418", client: "ABBEYDALE" },
  { code: "6419", client: "DIRECT" },
  { code: "6420", client: "DIRECT" },
  { code: "6421", client: "Metrum" },
  { code: "6422", client: "CAPITAL" },
  { code: "6423", client: "CAPITAL" },
  { code: "6424", client: "JTDOOLEY" },
  { code: "6425", client: "ABBEYDALE" },
  { code: "6426", client: "Tricolt" },
  { code: "6427", client: "RESPUBLICA" },
  { code: "6428", client: "Farquharson Construction" },
  { code: "6429", client: "FRAMECORE CONSTRUCTION" },
  { code: "6430", client: "DIRECT" },
  { code: "6431", client: "Tiber" },
  { code: "6432", client: "Farquharson Construction" },
  { code: "6433", client: "JTDOOLEY" },
  { code: "6434", client: "JTDOOLEY" },
  { code: "6435", client: "ABBEYDALE" },
  { code: "6436", client: "REDEFINE" },
  { code: "6437", client: "ABBEYDALE" },
  { code: "6438", client: "DIRECT" },
  { code: "6439", client: "WBHO" },
  { code: "6440", client: "Baucor" },
  { code: "6441", client: "RESPUBLICA" },
  { code: "6442", client: "Archstone Construction (PTY) LTD" },
  { code: "6443", client: "DIRECT" },
  { code: "6444", client: "DIRECT" },
  { code: "6445", client: "Mikebuyskes Construction" },
  { code: "6446", client: "M&M CONSTRUCTION" },
  { code: "6447", client: "DIRECT" },
  { code: "6448", client: "JOVAN" },
  { code: "6449", client: "JTDOOLEY" },
  { code: "6450", client: "BARROW" },
  { code: "6451", client: "Abbeydale" },
  { code: "6452", client: "BARROW" },
  { code: "6453", client: "BANTRY" },
  { code: "6454", client: "DIRECT" },
  { code: "6455", client: "Farquharson Construction" },
  { code: "6456", client: "RESPUBLICA" },
  { code: "6457", client: "BJV" },
  { code: "6458", client: "Tiber" },
  { code: "6459", client: "DIRECT" },
  { code: "6460", client: "FRAMECORE CONSTRUCTION" },
  { code: "6461", client: "WBHO" },
  { code: "6462", client: "DIRECT" },
  { code: "6463", client: "DIRECT" },
  { code: "6464", client: "GDM" },
  { code: "6465", client: "BEURDEN" },
  { code: "6466", client: "BARROW" },
  { code: "6467", client: "RESPUBLICA" },
  { code: "6468", client: "FRAMECORE CONSTRUCTION" },
  { code: "6469", client: "GDM" },
  { code: "6470", client: "Baucor" },
  { code: "6471", client: "Archstone Construction (PTY) LTD" },
  { code: "6472", client: "DIRECT" },
  { code: "6473", client: "RESPUBLICA" },
  { code: "6474", client: "Abbeydale" },
  { code: "6475", client: "Abbeydale" },
  { code: "6476", client: "DIRECT" },
  { code: "6477", client: "JTDOOLEY" },
  { code: "6478", client: "AFRICAN KINGDOM HOLDING" },
  { code: "6479", client: "ABBEYDALE" },
  { code: "6480", client: "ABBEYDALE" },
  { code: "6481", client: "Bantry" },
  { code: "6482", client: "direct" },
  { code: "6483", client: "DIRECT" },
  { code: "6484", client: "JTDOOLEY" },
  { code: "6485", client: "Direct" },
  { code: "6486", client: "DIRECT" },
  { code: "6487", client: "Millennium Construction (Pty) Ltd" },
  { code: "6488", client: "DIRECT" },
  { code: "6489", client: "GDM" },
  { code: "6490", client: "PROBEST" },
  { code: "6491", client: "Tricolt" },
  { code: "6492", client: "RESPUBLICA" },
  { code: "6493", client: "DIRECT" },
  { code: "6494", client: "JTSON" },
  { code: "6495", client: "DIRECT" },
  { code: "6496", client: "WBHO" },
  { code: "6497", client: "EXCELSUS" },
  { code: "6498", client: "EXCELSUS" },
  { code: "6499", client: "EXCELSUS" },
  { code: "6500", client: "BANTRY" },
  { code: "6501", client: "ABBEYDALE" },
  { code: "6502", client: "GDM" },
  { code: "6503", client: "DIRECT" },
  { code: "6504", client: "Abbeydale" },
  { code: "6505", client: "SRP" },
  { code: "6506", client: "Mikebuyskes Construction" },
  { code: "6507", client: "Kumkanikulani" },
  { code: "6508", client: "JTDOOLEY" },
  { code: "6509", client: "DIRECT" },
  { code: "6510", client: "ABBEYDALE" },
  { code: "6511", client: "Mikebuyskes Construction" },
  { code: "6512", client: "DIRECT" },
  { code: "6513", client: "BANTRY" },
  { code: "6514", client: "BANTRY" },
  { code: "6515", client: "DIRECT" },
  { code: "6516", client: "FRAMECORE CONSTRUCTION" },
  { code: "6517", client: "REDEFINE" },
  { code: "6519", client: "DIRECT" },
  { code: "6520", client: "REDEFINE" },
  { code: "6521", client: "Kumkanikulani" },
  { code: "6522", client: "GDM" },
  { code: "6523", client: "DIRECT" },
  { code: "6524", client: "DIRECT" },
  { code: "6525", client: "NDWALA" },
  { code: "6526", client: "BARROW" },
  { code: "6527", client: "Direct" },
  { code: "6528", client: "JCREFURB" },
  { code: "6529", client: "Mikebuyskes Construction" },
  { code: "6530", client: "BARROW" },
  { code: "6531", client: "DIRECT" },
  { code: "6532", client: "HEXAD" },
  { code: "6533", client: "BROLL" },
  { code: "6534", client: "Direct" },
  { code: "6535", client: "JCREFURB" },
  { code: "6536", client: "Mikebuyskes Construction" },
  { code: "6537", client: "DIRECT" },
  { code: "6538", client: "JTDOOLEY" },
  { code: "6539", client: "RESPUBLICA" },
  { code: "6540", client: "RESPUBLICA" },
  { code: "6541", client: "ABBEYDALE" },
  { code: "6542", client: "Farquharson Construction" },
  { code: "6543", client: "ABE" },
  { code: "6544", client: "EXCELLERATE JHI" },
  { code: "6545", client: "Kumkanikulani" },
  { code: "6546", client: "JTDOOLEY" },
  { code: "6547", client: "JCREFURB" },
  { code: "6548", client: "RESPUBLICA" },
  { code: "6549", client: "BAUCOR" },
  { code: "6550", client: "Direct" },
  { code: "6551", client: "SRP" },
  { code: "6552", client: "EXCELSUS" },
  { code: "6553", client: "W3O" },
  { code: "6554", client: "BAUCOR" },
  { code: "6555", client: "BAUCOR" },
  { code: "6556", client: "REDEFINE" },
  { code: "6557", client: "WBHO" },
  { code: "6558", client: "BANTRY" },
  { code: "6559", client: "DIRECT" },
  { code: "6560", client: "DIRECT" },
  { code: "6561", client: "Menlyn Maine" },
  { code: "6562", client: "EXCELSUS" },
  { code: "6563", client: "JCREFURB" },
  { code: "6564", client: "DIRECT" },
  { code: "6565", client: "ABE" },
  { code: "6566", client: "Direct" },
  { code: "6567", client: "PROBEST" },
  { code: "6568", client: "WBHO" },
  { code: "6569", client: "DIRECT" },
  { code: "6570", client: "DIRECT" },
  { code: "6571", client: "ABE" },
  { code: "6572", client: "M&M" },
  { code: "6573", client: "Mikebuyskes Construction" },
  { code: "6574", client: "DRACON" },
  { code: "6575", client: "BAUCOR" },
  { code: "6576", client: "Whip Retail" },
  { code: "6577", client: "DIRECT" },
  { code: "6578", client: "Direct" },
  { code: "6579", client: "REDEFINE" },
  { code: "6580", client: "Mikebuyskes Construction" },
  { code: "6581", client: "DIRECT" },
  { code: "6582", client: "Kumkani Khulani Contracting" },
  { code: "6583", client: "Abbeydale" },
  { code: "6584", client: "Mikebuyskes Construction" },
  { code: "6585", client: "SRP" },
  { code: "6586", client: "Archstone Construction (PTY) LTD" },
  { code: "6587", client: "JOVAN" },
  { code: "6588", client: "Direct" },
  { code: "6589", client: "Direct" },
  { code: "6590", client: "SKYSTONE" },
  { code: "6591", client: "Kumkani Khulani Contracting" },
  { code: "6592", client: "JTDOOLEY" },
  { code: "6593", client: "Abbeydale" },
  { code: "6594", client: "RESPUBLICA" },
  { code: "6595", client: "JTDOOLEY" },
  { code: "6596", client: "PROBEST" },
  { code: "6597", client: "Archstone Construction (PTY) LTD" },
  { code: "6598", client: "EXCELSUS" },
  { code: "6600", client: "Abbeydale" },
  { code: "6601", client: "DIRECT" },
  { code: "6602", client: "M&D" },
  { code: "6603", client: "Farquharson Construction" },
  { code: "6604", client: "BANTRY" },
  { code: "6605", client: "NDWALA" },
  { code: "6606", client: "BARROW" },
  { code: "6607", client: "JOVAN" },
  { code: "6608", client: "Archstone Construction (PTY) LTD" },
  { code: "6609", client: "DRACON" },
  { code: "6610", client: "DIRECT" },
  { code: "6611", client: "AFRICAN KINGDOM HOLDING" },
  { code: "6612", client: "DIRECT" },
  { code: "6613", client: "WBHO" },
  { code: "6614", client: "Kumkani Khulani Contracting" },
  { code: "6615", client: "DIRECT" },
  { code: "6616", client: "DIRECT" },
  { code: "6617", client: "W30" },
  { code: "6618", client: "DIRECT" },
  { code: "6619", client: "WBHO" },
  { code: "6620", client: "Abbeydale" },
  { code: "6621", client: "EXCELSUS" },
  { code: "6622", client: "BARROW" },
  { code: "6623", client: "Tricolt" },
  { code: "6624", client: "JTDOOLEY" },
  { code: "6625", client: "Abbeydale" },
  { code: "6626", client: "FRAMECORE CONSTRUCTION" },
  { code: "6627", client: "BANTRY" },
  { code: "6628", client: "BAUCOR" },
  { code: "6629", client: "DIRECT" },
  { code: "6630", client: "BAUCOR" },
  { code: "6631", client: "Mikebuyskes Construction" },
  { code: "6632", client: "Direct" },
  { code: "6633", client: "EXCELSUS" },
  { code: "6634", client: "Archstone Construction (PTY) LTD" },
  { code: "6635", client: "Archstone Construction (PTY) LTD" },
  { code: "6636", client: "RESPUBLICA" },
  { code: "6637", client: "Farquharson Construction" },
  { code: "6638", client: "LIBERA" },
  { code: "6639", client: "Tiber" },
  { code: "6640", client: "RESPUBLICA" },
  { code: "6641", client: "RESPUBLICA" },
  { code: "6642", client: "RESPUBLICA" },
  { code: "6643", client: "Mikebuyskes Construction" },
  { code: "6644", client: "RESPUBLICA" },
  { code: "6645", client: "Millennium Construction (Pty) Ltd" },
  { code: "6646", client: "RESPUBLICA" },
  { code: "6647", client: "Abbeydale" },
  { code: "6648", client: "JTDOOLEY" },
  { code: "6649", client: "BANTRY" },
  { code: "6650", client: "Abbeydale" },
  { code: "6651", client: "WBHO" },
  { code: "6652", client: "DIRECT" },
  { code: "6653", client: "DIRECT" },
  { code: "6654", client: "ABE" },
  { code: "6655", client: "EXCELSUS" },
  { code: "6656", client: "BAUCOR" },
  { code: "6657", client: "DIRECT" },
  { code: "6658", client: "Mikebuyskes Construction" },
  { code: "6659", client: "JTDOOLEY" },
  { code: "6660", client: "JTDOOLEY" },
  { code: "6661", client: "EXCELSUS" },
  { code: "6662", client: "BANTRY" },
  { code: "6663", client: "Archstone Construction (PTY) LTD" },
  { code: "6664", client: "Archstone Construction (PTY) LTD" },
  { code: "6665", client: "Archstone Construction (PTY) LTD" },
  { code: "6666", client: "Abbeydale" },
  { code: "6667", client: "Rocon" },
  { code: "6668", client: "REDEFINE" },
  { code: "6669", client: "DIRECT" },
  { code: "6670", client: "DIRECT" },
  { code: "6671", client: "STRIVE" },
  { code: "6672", client: "JRD ENGINEERING" },
  { code: "6673", client: "Millennium Construction (Pty) Ltd" },
  { code: "6674", client: "TRICOLT" },
  { code: "6675", client: "BROLL" },
  { code: "6676", client: "Direct" },
  { code: "6677", client: "Bartosch Construction" },
  { code: "6678", client: "JOVAN" },
  { code: "6679", client: "BARROW" },
  { code: "6680", client: "Mikebuyskes Construction" },
  { code: "6681", client: "DIRECT" },
  { code: "6682", client: "SKYSTONE" },
  { code: "6683", client: "RETNING" },
  { code: "6684", client: "ATTAQ" },
  { code: "6685", client: "DIRECT" },
  { code: "6686", client: "JOVAN" },
  { code: "6687", client: "BAUCOR" },
  { code: "6688", client: "LIBERA" },
  { code: "6689", client: "Bartosch Construction" },
  { code: "6690", client: "DIRECT" },
  { code: "6691", client: "METRUM" },
  { code: "6692", client: "Abbeydale" },
  { code: "6693", client: "BARROW" },
  { code: "6694", client: "DIRECT" },
  { code: "6695", client: "Abbeydale" },
  { code: "6696", client: "DIRECT" },
  { code: "6697", client: "AIRWAVES" },
  { code: "6698", client: "DIRECT" },
  { code: "6699", client: "JOVAN" },
  { code: "6700", client: "Abbeydale" },
  { code: "6701", client: "DIRECT" },
  { code: "6702", client: "DIRECT" },
  { code: "6703", client: "EXCELSUS" },
  { code: "6704", client: "Millennium Construction" },
  { code: "6705", client: "METRUM" },
  { code: "6706", client: "DIRECT" },
  { code: "6707", client: "Tiber" },
  { code: "6708", client: "FRAMECORE CONSTRUCTION" },
  { code: "6709", client: "TIBER" },
  { code: "6710", client: "DIRECT" },
  { code: "6711", client: "AFRICAN KINGDOM HOLDING" },
  { code: "6712", client: "BARROW" },
  { code: "6713", client: "Abbeydale" },
  { code: "6714", client: "NDWALA" },
  { code: "6715", client: "DIRECT" },
  { code: "6716", client: "Mikebuyskes Construction" },
  { code: "6717", client: "JTDOOLEY" },
  { code: "6718", client: "Abbeydale" },
  { code: "6719", client: "DIRECT" },
  { code: "6720", client: "Abbeydale" },
  { code: "6721", client: "Abbeydale" },
  { code: "6722", client: "DIRECT" },
  { code: "6723", client: "DIRECT" },
];

async function main() {
  console.log(`Seeding client names for ${siteClientSeeds.length} sites...`);

  let updated = 0;
  let notFound = 0;
  const missing: string[] = [];

  for (const row of siteClientSeeds) {
    const result = await prisma.site.updateMany({
      where: { code: row.code },
      data: { client: normalizeClientName(row.client) },
    });

    if (result.count > 0) {
      updated += result.count;
    } else {
      notFound++;
      missing.push(row.code);
    }
  }

  console.log(`Done. Updated: ${updated} sites, Not found: ${notFound}`);
  if (missing.length > 0) {
    console.log(`Missing site codes: ${missing.join(", ")}`);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error("Seed error:", e);
    await prisma.$disconnect();
    process.exit(1);
  });
