import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client.js";

const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

type ClaimSeed = {
  siteCode: string;
  claimType: string;
  claimDateLabel: string;
  claimOwner: string;
  client: string;
  comments?: string;
};

const march2026ClaimSeeds: ClaimSeed[] = [
  // GRIFFITH
  {
    siteCode: "5960",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "WBHO",
  },
  {
    siteCode: "6328",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "WBHO",
  },
  {
    siteCode: "6461",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "WBHO",
  },
  {
    siteCode: "6558",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "Bantry",
  },
  {
    siteCode: "6568",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "WBHO",
  },
  {
    siteCode: "6600",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Griffith",
    client: "Abbeydale",
  },
  {
    siteCode: "6603",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "Farquharson",
  },
  {
    siteCode: "6619",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "WBHO",
  },
  {
    siteCode: "6678",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Griffith",
    client: "Jovan",
  },
  {
    siteCode: "6686",
    claimType: "TAU",
    claimDateLabel: "3rd",
    claimOwner: "Griffith",
    client: "Jovan",
  },
  {
    siteCode: "6689",
    claimType: "LPS",
    claimDateLabel: "LPS",
    claimOwner: "Griffith",
    client: "Bartosch",
  },
  {
    siteCode: "6691",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "Metrum",
  },
  {
    siteCode: "6696",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Griffith",
    client: "Direct",
  },
  {
    siteCode: "6699",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Griffith",
    client: "Jovan",
  },
  {
    siteCode: "6705",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Griffith",
    client: "Metrum",
  },
  // THEMBA
  {
    siteCode: "5619",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Themba",
    client: "Mshandukani",
  },
  {
    siteCode: "6353",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Themba",
    client: "Bantry",
  },
  {
    siteCode: "6435",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Themba",
    client: "Abbeydale",
  },
  {
    siteCode: "6446",
    claimType: "TAU",
    claimDateLabel: "21st",
    claimOwner: "Themba",
    client: "M&M",
  },
  {
    siteCode: "6455",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Themba",
    client: "Farquharson",
  },
  {
    siteCode: "6469",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Themba",
    client: "GDM",
  },
  {
    siteCode: "6493",
    claimType: "DW",
    claimDateLabel: "30th",
    claimOwner: "Themba",
    client: "Direct",
  },
  {
    siteCode: "6497",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Themba",
    client: "Excelsus",
  },
  {
    siteCode: "6571",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Themba",
    client: "ABE",
  },
  {
    siteCode: "6572",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Themba",
    client: "M&M",
  },
  {
    siteCode: "6573",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Themba",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6584",
    claimType: "TAU",
    claimDateLabel: "6th",
    claimOwner: "Themba",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6586",
    claimType: "TAU",
    claimDateLabel: "10th",
    claimOwner: "Themba",
    client: "Archstone",
  },

  // LAWRENCE
  {
    siteCode: "6291",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lawrence",
    client: "Baucor",
  },
  {
    siteCode: "6316",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lawrence",
    client: "Tiber",
  },
  {
    siteCode: "6381",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "JTDooley",
  },
  {
    siteCode: "6450",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "Barrow",
  },
  {
    siteCode: "6473",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Respublica",
  },
  {
    siteCode: "6565",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lawrence",
    client: "ABE",
  },
  {
    siteCode: "6592",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "JTDooley",
  },
  {
    siteCode: "6595",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "JTDooley",
  },
  {
    siteCode: "6616",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Direct",
  },
  {
    siteCode: "6632",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Direct",
  },
  {
    siteCode: "6639",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lawrence",
    client: "Tiber",
  },
  {
    siteCode: "6646",
    claimType: "TAU",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Respublica",
  },
  {
    siteCode: "6648",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "JTDooley",
  },
  {
    siteCode: "6654",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Lawrence",
    client: "ABE",
  },
  {
    siteCode: "6659",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "JTDooley",
  },
  {
    siteCode: "6660",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "JTDooley",
  },
  {
    siteCode: "6661",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "Excelsus",
  },
  {
    siteCode: "6670",
    claimType: "TAU",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Direct",
  },
  {
    siteCode: "6685",
    claimType: "TAU",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Direct",
  },
  {
    siteCode: "6694",
    claimType: "LPS",
    claimDateLabel: "",
    claimOwner: "Lawrence",
    client: "Direct",
  },
  {
    siteCode: "6709",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Lawrence",
    client: "Tiber",
  },
  {
    siteCode: "6712",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lawrence",
    client: "Barrow",
  },

  // THOUSAND
  {
    siteCode: "5083",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Thousand",
    client: "JTDooley",
  },
  {
    siteCode: "6309",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Direct",
  },
  {
    siteCode: "6358",
    claimType: "LPS",
    claimDateLabel: "22nd",
    claimOwner: "Thousand",
    client: "Direct",
  },
  {
    siteCode: "6388",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Thousand",
    client: "Ndwala",
  },
  {
    siteCode: "6407",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Thousand",
    client: "HEXAD",
  },
  {
    siteCode: "6418",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Abbeydale",
  },
  {
    siteCode: "6426",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Thousand",
    client: "TRICOLT",
  },
  {
    siteCode: "6431",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Tiber",
  },
  {
    siteCode: "6475",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Thousand",
    client: "Abbeydale",
  },
  {
    siteCode: "6487",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Thousand",
    client: "Millcon",
  },
  {
    siteCode: "6543",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Thousand",
    client: "ABE",
  },
  {
    siteCode: "6604",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Bantry",
  },
  {
    siteCode: "6617",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Thousand",
    client: "W30",
  },
  {
    siteCode: "6624",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Thousand",
    client: "JTDooley",
  },
  {
    siteCode: "6634",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Thousand",
    client: "Archstone",
  },
  {
    siteCode: "6649",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Bantry",
  },
  {
    siteCode: "6690",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Strive",
  },
  {
    siteCode: "6692",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Thousand",
    client: "Abbeydale",
  },
  {
    siteCode: "6707",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Thousand",
    client: "Tiber",
  },
  {
    siteCode: "6715",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Thousand",
    client: "Direct",
  },

  // LUCAS
  {
    siteCode: "6248",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Archstone",
    comments: "additional work done",
  },
  {
    siteCode: "6312",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "JTSon",
  },
  {
    siteCode: "6356",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Bantry",
  },
  {
    siteCode: "6357",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "African kingdom holding",
  },
  {
    siteCode: "6512",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Lucas",
    client: "Direct",
  },
  {
    siteCode: "6525",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lucas",
    client: "Ndwala",
  },
  {
    siteCode: "6541",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Abbeydale",
  },
  {
    siteCode: "6562",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Excelsus",
  },
  {
    siteCode: "6605",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lucas",
    client: "Ndwala",
  },
  {
    siteCode: "6620",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Abbeydale",
  },
  {
    siteCode: "6621",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Excelsus",
  },
  {
    siteCode: "6643",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Lucas",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6647",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lucas",
    client: "Abbeydale",
  },
  {
    siteCode: "6656",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lucas",
    client: "Baucor",
  },
  {
    siteCode: "6658",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lucas",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6681",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Lucas",
    client: "Direct",
  },
  {
    siteCode: "6687",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Lucas",
    client: "Baucor",
  },
  {
    siteCode: "6688",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Lucas",
    client: "Libera",
  },
  {
    siteCode: "6698",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Lucas",
    client: "Direct",
  },
  {
    siteCode: "6700",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Lucas",
    client: "Abbeydale",
  },
  {
    siteCode: "6711",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Lucas",
    client: "African kingdom holding",
  },

  // OWEN
  {
    siteCode: "5535",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "DIRECT",
  },
  {
    siteCode: "6236",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Owen",
    client: "TRICOLT",
    comments: "Anything additional to be claimed?",
  },
  {
    siteCode: "6396",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Owen",
    client: "GDM",
  },
  {
    siteCode: "6472",
    claimType: "LPS",
    claimDateLabel: "25th",
    claimOwner: "Owen",
    client: "MLC",
  },
  {
    siteCode: "6490",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Owen",
    client: "Probest",
  },
  {
    siteCode: "6500",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Owen",
    client: "Bantry",
  },
  {
    siteCode: "6517",
    claimType: "LPS",
    claimDateLabel: "20th",
    claimOwner: "Owen",
    client: "Redefine",
  },
  {
    siteCode: "6520",
    claimType: "LPS",
    claimDateLabel: "20th",
    claimOwner: "Owen",
    client: "Redefine",
  },
  {
    siteCode: "6589",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "STRIVE",
  },
  {
    siteCode: "6596",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Probest",
  },
  {
    siteCode: "6602",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Owen",
    client: "M&D",
  },
  {
    siteCode: "6618",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Direct",
  },
  {
    siteCode: "6622",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Barrow",
  },
  {
    siteCode: "6628",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Baucor",
  },
  {
    siteCode: "6637",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Owen",
    client: "Farquharson",
  },
  {
    siteCode: "6645",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Millcon",
  },
  {
    siteCode: "6667",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Owen",
    client: "Rocon",
  },
  {
    siteCode: "6669",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Direct",
  },
  {
    siteCode: "6673",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Owen",
    client: "Millcon",
  },
  {
    siteCode: "6674",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "TRICOLT",
  },
  {
    siteCode: "6677",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Owen",
    client: "Bartosch",
  },
  {
    siteCode: "6679",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Owen",
    client: "Barrow",
  },
  {
    siteCode: "6704",
    claimType: "TAU",
    claimDateLabel: "COC",
    claimOwner: "Owen",
    client: "Millcon",
  },

  // MAWESI
  {
    siteCode: "6105",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Direct",
  },
  {
    siteCode: "6411",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Mawesi",
    client: "DLR",
    comments: "Is there anything extra to claim?",
  },
  {
    siteCode: "6474",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Mawesi",
    client: "Abbeydale",
  },
  {
    siteCode: "6502",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Mawesi",
    client: "GDM",
  },
  {
    siteCode: "6532",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Mawesi",
    client: "HEXAD",
  },
  {
    siteCode: "6544",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Mawesi",
    client: "Direct",
  },
  {
    siteCode: "6548",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Mawesi",
    client: "Respublica",
  },
  {
    siteCode: "6552",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Excelsus",
  },
  {
    siteCode: "6561",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Direct",
  },
  {
    siteCode: "6598",
    claimType: "TAU",
    claimDateLabel: "COC",
    claimOwner: "Mawesi",
    client: "Excelsus",
  },
  {
    siteCode: "6601",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Mawesi",
    client: "Direct",
  },
  {
    siteCode: "6606",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Mawesi",
    client: "Barrow",
  },
  {
    siteCode: "6636",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Mawesi",
    client: "Respublica",
  },
  {
    siteCode: "6640",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Mawesi",
    client: "Respublica",
  },
  {
    siteCode: "6641",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Mawesi",
    client: "Respublica",
  },
  {
    siteCode: "6642",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Mawesi",
    client: "Respublica",
  },
  {
    siteCode: "6655",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Excelsus",
  },
  {
    siteCode: "6665",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Archstone",
  },
  {
    siteCode: "6675",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Broll",
  },
  {
    siteCode: "6683",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Mawesi",
    client: "Retning",
  },

  // NICOLAS & CAUTIOUS
  {
    siteCode: "6156",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6214",
    claimType: "TAU",
    claimDateLabel: "10th",
    claimOwner: "Nicolas & Cautious",
    client: "Metrum(EB Construction)",
    comments: "Final claim",
  },
  {
    siteCode: "6252",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Bantry",
    comments: "Extras and snags to be claimed",
  },
  {
    siteCode: "6317",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Abbeydale",
    comments: "Dayworks please",
  },
  {
    siteCode: "6368",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Abbeydale",
    comments: "Dayworks please",
  },
  {
    siteCode: "6382",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Baucor",
    comments: "Dayworks please",
  },
  {
    siteCode: "6451",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Abbeydale",
  },
  {
    siteCode: "6458",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Tiber",
    comments: "Dayworks please",
  },
  {
    siteCode: "6471",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6479",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Abbeydale",
  },
  {
    siteCode: "6511",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Nicolas & Cautious",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6537",
    claimType: "LPS",
    claimDateLabel: "20th",
    claimOwner: "Nicolas & Cautious",
    client: "Direct",
  },
  {
    siteCode: "6551",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "SRP",
  },
  {
    siteCode: "6559",
    claimType: "LPS",
    claimDateLabel: "20th",
    claimOwner: "Nicolas & Cautious",
    client: "Direct",
  },
  {
    siteCode: "6580",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6587",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "JOVAN",
  },
  {
    siteCode: "6590",
    claimType: "TAU",
    claimDateLabel: "6th",
    claimOwner: "Nicolas & Cautious",
    client: "Skystone",
  },
  {
    siteCode: "6597",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6599",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6608",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6631",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6633",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Excelsus",
  },
  {
    siteCode: "6635",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6644",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Respublica",
  },
  {
    siteCode: "6657",
    claimType: "TAU",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Direct",
  },
  {
    siteCode: "6662",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Bantry",
  },
  {
    siteCode: "6663",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6664",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Nicolas & Cautious",
    client: "Archstone",
  },
  {
    siteCode: "6668",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Redefine",
  },
  {
    siteCode: "6672",
    claimType: "LPS",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "JRD Engineering",
  },
  {
    siteCode: "6680",
    claimType: "TAU",
    claimDateLabel: "11th",
    claimOwner: "Nicolas & Cautious",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6682",
    claimType: "TAU",
    claimDateLabel: "6th",
    claimOwner: "Nicolas & Cautious",
    client: "Skystone",
  },
  {
    siteCode: "6697",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Airwaves",
  },
  {
    siteCode: "6702",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Direct",
  },
  {
    siteCode: "6706",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Nicolas & Cautious",
    client: "Direct",
  },
  {
    siteCode: "6710",
    claimType: "LPS",
    claimDateLabel: "MONTHLY",
    claimOwner: "Nicolas & Cautious",
    client: "Direct",
  },
  {
    siteCode: "6714",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Nicolas & Cautious",
    client: "Ndwala",
  },

  // GEOFFREY
  {
    siteCode: "6195",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Geoffrey",
    client: "W30",
  },
  {
    siteCode: "6355",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Geoffrey",
    client: "Mikebuyskes",
  },
  {
    siteCode: "6439",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Geoffrey",
    client: "WBHO",
  },
  {
    siteCode: "6468",
    claimType: "TAU",
    claimDateLabel: "12th",
    claimOwner: "Geoffrey",
    client: "Framecore",
  },
  {
    siteCode: "6501",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6510",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6553",
    claimType: "TAU",
    claimDateLabel: "6th",
    claimOwner: "Geoffrey",
    client: "W30",
  },
  {
    siteCode: "6557",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Geoffrey",
    client: "WBHO",
  },
  {
    siteCode: "6583",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6593",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6594",
    claimType: "LPS",
    claimDateLabel: "20th",
    claimOwner: "Geoffrey",
    client: "Respublica",
  },
  {
    siteCode: "6607",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Geoffrey",
    client: "JOVAN",
  },
  {
    siteCode: "6613",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Geoffrey",
    client: "WBHO",
  },
  {
    siteCode: "6626",
    claimType: "TAU",
    claimDateLabel: "19th",
    claimOwner: "Geoffrey",
    client: "Framecore",
  },
  {
    siteCode: "6650",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6651",
    claimType: "DW",
    claimDateLabel: "COC",
    claimOwner: "Geoffrey",
    client: "WBHO",
  },
  {
    siteCode: "6666",
    claimType: "TAU",
    claimDateLabel: "13th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6671",
    claimType: "LPS",
    claimDateLabel: "COC",
    claimOwner: "Geoffrey",
    client: "DIRECT",
  },
  {
    siteCode: "6695",
    claimType: "TAU",
    claimDateLabel: "20th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
  {
    siteCode: "6708",
    claimType: "TAU",
    claimDateLabel: "17th",
    claimOwner: "Geoffrey",
    client: "Framecore",
  },
  {
    siteCode: "6713",
    claimType: "TAU",
    claimDateLabel: "18th",
    claimOwner: "Geoffrey",
    client: "Abbeydale",
  },
];

function parseDay(label: string): number | null {
  const m = label.match(/\d+/);
  if (!m) return null;
  const day = Number(m[0]);
  if (!Number.isInteger(day) || day < 1 || day > 31) return null;
  return day;
}

async function main() {
  let updated = 0;
  let missing = 0;

  for (const seed of march2026ClaimSeeds) {
    const site = await prisma.site.findFirst({
      where: { code: seed.siteCode },
      select: { id: true },
    });

    if (!site) {
      console.warn(`No site found for code ${seed.siteCode}`);
      missing++;
      continue;
    }

    const day = parseDay(seed.claimDateLabel);
    if (!day) {
      console.warn(
        `Seed for site ${seed.siteCode} has non-numeric claimDateLabel='${seed.claimDateLabel}', skipping siteClaimDate`,
      );
      continue;
    }

    const date = new Date(Date.UTC(2026, 2, day)); // March = month index 2

    await prisma.site.update({
      where: { id: site.id },
      data: {
        siteClaimDate: date,
      },
    });
    updated++;
  }

  console.log(
    `Done. Updated siteClaimDate for ${updated} sites. Missing sites: ${missing}.`,
  );
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error("Seed error:", e);
    await prisma.$disconnect();
    process.exit(1);
  });
