name: Deploy FCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        run: |
          cd /opt/apps/fcp
          git fetch origin
          git reset --hard origin/main

      - name: Rebuild Docker
        run: |
          cd /opt/apps/fcp
          docker compose up -d --build

      - name: Cleanup old images
        run: docker image prune -f